---
- name: Add Docker repository [Red Hat]
  become: yes
  yum_repository:
    name: docker
    description: Docker YUM repository
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  when: ansible_os_family == "RedHat"

- name: Install Docker and it's dependencies [Red Hat]
  become: yes
  yum:
    name: ["docker-ce","docker-ce-cli","containerd.io"]
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install prerequisites [Debian]
  become: yes
  apt:
    name: ["apt-transport-https","ca-certificates","curl","gnupg","lsb-release"]
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Import Docker GPG signing key [Debian]
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository [Debian]
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Docker and its dependencies
  become: yes
  apt:
    name: ["docker-ce","docker-ce-cli","containerd.io"]
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"
