FROM ubuntu:latest

LABEL "maintainer"="Protofire"

RUN mkdir -p /theta_mainnet/bin /theta_mainnet/guardian_mainnet/node && \
    apt update && \
    apt install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    curl -k --output /theta_mainnet/bin/theta `curl -k 'https://mainnet-data.thetatoken.org/binary?os=linux&name=theta'` && \
    curl -k --output /theta_mainnet/guardian_mainnet/node/config.yaml `curl -k 'https://mainnet-data.thetatoken.org/config?is_guardian=true'` && \
    chmod +x /theta_mainnet/bin/theta

RUN curl -k --output /theta_mainnet/bin/thetacli `curl -k 'https://mainnet-data.thetatoken.org/binary?os=linux&name=thetacli'` && \
    chmod +x /theta_mainnet/bin/thetacli

VOLUME ["/theta_mainnet/guardian_mainnet/node"]

EXPOSE 30001 16888

ENTRYPOINT ["/theta_mainnet/bin/theta"]

CMD ["start"]